// <auto-generated />
using System;
using LiftMate.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiftMate.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260629190807_AddWorkoutSetDeletedAt")]
    partial class AddWorkoutSetDeletedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiftMate.Api.Auth.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LiftMateRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("TrainerLinkedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TrainerUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TrainerUserId");

                    b.ToTable("AspNetUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AspNetUsers_LiftMateRole", "[LiftMateRole] IN ('trainer', 'trainee')");
                        });
                });

            modelBuilder.Entity("LiftMate.Api.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("LiftMate.Api.Auth.TrainerInviteCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TrainerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TrainerUserId")
                        .IsUnique();

                    b.ToTable("TrainerInviteCodes");
                });

            modelBuilder.Entity("LiftMate.Api.SharedSessions.PostWorkoutFeedback", b =>
                {
                    b.Property<Guid>("SharedSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("WellbeingRating")
                        .HasColumnType("int");

                    b.HasKey("SharedSessionId");

                    b.ToTable("PostWorkoutFeedbacks", t =>
                        {
                            t.HasCheckConstraint("CK_PostWorkoutFeedbacks_WellbeingRating", "[WellbeingRating] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("LiftMate.Api.SharedSessions.SharedSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(90);

                    b.Property<string>("StartedByRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StartedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TraineeUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrainerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WorkoutSetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkoutSetName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("StartedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("TraineeUserId")
                        .IsUnique()
                        .HasFilter("[Status] = 'active'");

                    b.HasIndex("TrainerUserId");

                    b.HasIndex("WorkoutSetId");

                    b.ToTable("SharedSessions", t =>
                        {
                            t.HasCheckConstraint("CK_SharedSessions_RestSeconds", "[RestSeconds] BETWEEN 15 AND 600");

                            t.HasCheckConstraint("CK_SharedSessions_StartedByRole", "[StartedByRole] IN ('trainer', 'trainee')");

                            t.HasCheckConstraint("CK_SharedSessions_Status", "[Status] IN ('active', 'completed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("LiftMate.Api.SharedSessions.SharedSessionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExerciseOrder")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsDone")
                        .HasColumnType("bit");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("SetIndex")
                        .HasColumnType("int");

                    b.Property<Guid>("SharedSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid?>("WorkoutSetRowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("ExerciseType");

                    b.HasIndex("SharedSessionId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("WorkoutSetRowId");

                    b.HasIndex("SharedSessionId", "ExerciseOrder", "SetIndex");

                    b.ToTable("SharedSessionValues", t =>
                        {
                            t.HasCheckConstraint("CK_SharedSessionValues_ExerciseType", "[ExerciseType] IN ('repsWeight', 'repsOnly', 'time')");
                        });
                });

            modelBuilder.Entity("LiftMate.Api.TrainerGuidance.TrainerGuidance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EvidenceJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TraineeUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TraineeUserId", "ReadAt", "CreatedAt");

                    b.HasIndex("TraineeUserId", "Type", "ExerciseId", "Fingerprint")
                        .IsUnique()
                        .HasFilter("[ExerciseId] IS NOT NULL");

                    b.ToTable("TrainerGuidance", t =>
                        {
                            t.HasCheckConstraint("CK_TrainerGuidance_Type", "[Type] IN ('weight_stagnation', 'low_wellbeing')");
                        });
                });

            modelBuilder.Entity("LiftMate.Api.TrainingProgress.WorkoutProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SourceCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SourceSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TraineeUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("WorkoutSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SourceSessionId")
                        .IsUnique();

                    b.HasIndex("WorkoutSetId");

                    b.HasIndex("TraineeUserId", "WorkoutSetId")
                        .IsUnique();

                    b.ToTable("WorkoutProgresses");
                });

            modelBuilder.Entity("LiftMate.Api.TrainingProgress.WorkoutProgressValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Seconds")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("WorkoutProgressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WorkoutSetRowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutProgressId", "WorkoutSetRowId")
                        .IsUnique();

                    b.ToTable("WorkoutProgressValues", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutProgressValues_ExerciseType", "[ExerciseType] IN ('repsWeight', 'repsOnly', 'time')");
                        });
                });

            modelBuilder.Entity("LiftMate.Api.WeeklyStreaks.TraineeWeeklyStreak", b =>
                {
                    b.Property<string>("TraineeUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BestStreak")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentStreakAtLastActiveWeek")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastActiveWeekStart")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastCompletedSessionAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TraineeUserId");

                    b.ToTable("TraineeWeeklyStreaks", t =>
                        {
                            t.HasCheckConstraint("CK_TraineeWeeklyStreaks_BestStreak", "[BestStreak] >= 0");

                            t.HasCheckConstraint("CK_TraineeWeeklyStreaks_CurrentStreak", "[CurrentStreakAtLastActiveWeek] >= 0");
                        });
                });

            modelBuilder.Entity("LiftMate.Api.WorkoutSets.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RestSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(90);

                    b.Property<string>("TrainerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TrainerUserId");

                    b.HasIndex("TrainerUserId", "DeletedAt");

                    b.ToTable("WorkoutSets", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSets_RestSeconds", "[RestSeconds] BETWEEN 15 AND 600");
                        });
                });

            modelBuilder.Entity("LiftMate.Api.WorkoutSets.WorkoutSetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AssignedByTrainerUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TraineeUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("WorkoutSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TraineeUserId");

                    b.HasIndex("WorkoutSetId");

                    b.HasIndex("WorkoutSetId", "TraineeUserId")
                        .IsUnique();

                    b.ToTable("WorkoutSetAssignments");
                });

            modelBuilder.Entity("LiftMate.Api.WorkoutSets.WorkoutSetRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ExerciseOrder")
                        .HasColumnType("int");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("Reps")
                        .HasColumnType("int");

                    b.Property<int?>("Seconds")
                        .HasColumnType("int");

                    b.Property<int>("SetIndex")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("WorkoutSetId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseType");

                    b.HasIndex("WorkoutSetId");

                    b.HasIndex("WorkoutSetId", "ExerciseId", "SetIndex");

                    b.HasIndex("WorkoutSetId", "ExerciseOrder", "SetIndex");

                    b.ToTable("WorkoutSetRows", t =>
                        {
                            t.HasCheckConstraint("CK_WorkoutSetRows_ExerciseType", "[ExerciseType] IN ('repsWeight', 'repsOnly', 'time')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LiftMate.Api.Auth.ApplicationUser", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "TrainerUser")
                        .WithMany("Trainees")
                        .HasForeignKey("TrainerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TrainerUser");
                });

            modelBuilder.Entity("LiftMate.Api.Auth.RefreshToken", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LiftMate.Api.Auth.TrainerInviteCode", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "TrainerUser")
                        .WithMany()
                        .HasForeignKey("TrainerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainerUser");
                });

            modelBuilder.Entity("LiftMate.Api.SharedSessions.PostWorkoutFeedback", b =>
                {
                    b.HasOne("LiftMate.Api.SharedSessions.SharedSession", "SharedSession")
                        .WithOne("Feedback")
                        .HasForeignKey("LiftMate.Api.SharedSessions.PostWorkoutFeedback", "SharedSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedSession");
                });

            modelBuilder.Entity("LiftMate.Api.SharedSessions.SharedSession", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "StartedByUser")
                        .WithMany()
                        .HasForeignKey("StartedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "TraineeUser")
                        .WithMany()
                        .HasForeignKey("TraineeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "TrainerUser")
                        .WithMany()
                        .HasForeignKey("TrainerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LiftMate.Api.WorkoutSets.WorkoutSet", "WorkoutSet")
                        .WithMany()
                        .HasForeignKey("WorkoutSetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StartedByUser");

                    b.Navigation("TraineeUser");

                    b.Navigation("TrainerUser");

                    b.Navigation("WorkoutSet");
                });

            modelBuilder.Entity("LiftMate.Api.SharedSessions.SharedSessionValue", b =>
                {
                    b.HasOne("LiftMate.Api.SharedSessions.SharedSession", "SharedSession")
                        .WithMany("Values")
                        .HasForeignKey("SharedSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SharedSession");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("LiftMate.Api.TrainingProgress.WorkoutProgress", b =>
                {
                    b.HasOne("LiftMate.Api.WorkoutSets.WorkoutSet", "WorkoutSet")
                        .WithMany()
                        .HasForeignKey("WorkoutSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkoutSet");
                });

            modelBuilder.Entity("LiftMate.Api.TrainingProgress.WorkoutProgressValue", b =>
                {
                    b.HasOne("LiftMate.Api.TrainingProgress.WorkoutProgress", "WorkoutProgress")
                        .WithMany("Values")
                        .HasForeignKey("WorkoutProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgress");
                });

            modelBuilder.Entity("LiftMate.Api.WeeklyStreaks.TraineeWeeklyStreak", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "TraineeUser")
                        .WithMany()
                        .HasForeignKey("TraineeUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraineeUser");
                });

            modelBuilder.Entity("LiftMate.Api.WorkoutSets.WorkoutSet", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "TrainerUser")
                        .WithMany()
                        .HasForeignKey("TrainerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrainerUser");
                });

            modelBuilder.Entity("LiftMate.Api.WorkoutSets.WorkoutSetAssignment", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", "TraineeUser")
                        .WithMany()
                        .HasForeignKey("TraineeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LiftMate.Api.WorkoutSets.WorkoutSet", "WorkoutSet")
                        .WithMany("Assignments")
                        .HasForeignKey("WorkoutSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraineeUser");

                    b.Navigation("WorkoutSet");
                });

            modelBuilder.Entity("LiftMate.Api.WorkoutSets.WorkoutSetRow", b =>
                {
                    b.HasOne("LiftMate.Api.WorkoutSets.WorkoutSet", "WorkoutSet")
                        .WithMany("Rows")
                        .HasForeignKey("WorkoutSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutSet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LiftMate.Api.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LiftMate.Api.Auth.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Trainees");
                });

            modelBuilder.Entity("LiftMate.Api.SharedSessions.SharedSession", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("LiftMate.Api.TrainingProgress.WorkoutProgress", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("LiftMate.Api.WorkoutSets.WorkoutSet", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
